services:
  # ===============================
  # DEVELOPMENT ENVIRONMENT
  # ===============================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herpes
    image: danielthalmann/herpes
    environment:
      APP_NAME: Herpes
      APP_ENV: local
      APP_DEBUG: 'false'
      APP_URL: http://localhost:${APP_PORT:-8000}
      DB_CONNECTION: sqlite
      LOG_FILE: /app/storage/logs/entrypoint.log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/metrics"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '${APP_PORT_SSL:-8443}:443'
      - '${APP_PORT:-8000}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - '.:/app'
    profiles:
      - dev
    networks:
      - mynetwork

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herpes-queue
    image: danielthalmann/herpes
    command: php artisan queue:work
    depends_on:
      app:
        condition: service_healthy # Attend que tout soit totalement prête
    environment:
      WORKER: "true"
      APP_NAME: Herpes
      APP_ENV: local
      APP_DEBUG: 'false'
      APP_URL: http://localhost:${APP_PORT:-8000}
      DB_CONNECTION: sqlite
      LOG_FILE: /app/storage/logs/entrypoint-queue.log
    volumes:
      - '.:/app'
    profiles:
      - dev
    networks:
      - mynetwork

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herpes-cron
    image: danielthalmann/herpes
    command: cron -f
    environment:
      WORKER: "true"
      APP_NAME: Herpes
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://localhost:${APP_PORT:-8000}
      DB_CONNECTION: sqlite
      LOG_FILE: /app/storage/logs/entrypoint-cron.log
    depends_on:
      app:
        condition: service_healthy # Attend que tout soit totalement prête
    volumes:
      - '.:/app'
    profiles:
      - dev
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
    name: mynetwork


